travis:
  secure:
    BINSTAR_TOKEN: bMw36JH+E/Q37dEEqeqbGTlqrdvCM8xPBWj/27lUoNR3vwA0X5DMBGn1XqrVum8ZV3WB3rlgHv5IH6rl1gCL1q18piHpiu5wWxOOGK5m2RrVj1gj9OPsU91h6R+00xPGUPUVxyQdxV6MGVYrm2Azl2K6hP51Ca6V95i2bxAXkUmECn1x6pTffiSJWBTAlMAmB4y04pUs4XchHkaHzceDB+TYzSLFOJUEyYwQ5fujO4EV8eFzRc38BIvUT0pa+8qNQ742k+bWKSavrOMCcrwKQzmq3xjldGm1fsFjiHF0ySssyQPIcafCnPxLsAnR4idB6J6az1Ybb296mgX/tgqkwijk5zDX4pNSbSJlDeNrQrtzD1RSnk2Uyiij3IeT6jxpXQFxxzBP+8AmGSkc1zpcex7LgXQBDl0j8xFvKhvlWjaK5sX5fiQjZuyiu38Y9yGlegfjVPi9sw5XCse/IyOVRS+a4W8YUG11i37eSgmQDAZUk9w0r+MC5btLRIx+wck8hIFtcRWn1vnIotRq0h0Gs4lqOycPcp+lHi5QcxxEA5DJJdOqKL+pU39J5kLWa+LDF0lCPzTSuH4PLB81CKMRZpphu55mvBf4a9TddOVJnQ5iEKOyu2D+cKa02vyRRLH7VknLk4GML749P/zYhP2E5xCozOeDJj8RCz7UYksZMRI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
