travis:
  secure:
    BINSTAR_TOKEN: m2eu2vI0v067jltdN7cPM3aXgFGRQvhzM+9sK/nxrMkEfIKiJK6CJgshiVE5Yd2zfb2mrvDxFb/dCQFaXB5VCIKVr93ftPiiJzkskN5DPuoIDMtjj3LWAwpRbgdZI+VLDwahGz9MaZu31MtVwVStdPgVMiPAtNQxaUrdLQkWgcSYnr3Fn3/RiAz8mLQiWK0EallYfQ6zzCKAOp15lqtCdagpNLxXgwoR2n4XLMOMJkYg7yJ3nefkW2Dy1dg6UitkZDGOEpkgE+7lNaHQPQj/sezgAvdeykJa+3Qx8Y8q3lwUsDy05UHXdsJZlhKNV1KcPeRi+anxsgiRhikMAAPA0DbIPZvTPbP1jaqsn1fnUICNWwM1LC6f4uubYEkIh40IYzloUig/L7+Yuz90RZp0St9eHY2jUsxcgaywjELdFx0XVIQlWYMlwd60qEGde+jmoe7KdtdifhTQKViRnrdnr4z3BK5cH8dBjg+Om+bUquXpSdIRoWbKh649DQuApkwJUytb2Y//B3pofq4CWwJsZ9JiWdwEnLDKkHzs43pOTsHOUgErWEoYRF9FarUxHOrf+CZQ+nhpYJ4qNFKqJTGRvA4JjDH3Z7NMlLHqXGTnehou7jkBi2l3Ouum9DlfMBkXTUBvbDVfcwRkywcNc06+HY7YYAyn0ZbmIUKwsyPxYjQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
