travis:
  secure:
    BINSTAR_TOKEN: WjZYSgaoOKD8LysEVSeuOKTH5+LyaVI0IShxmr8Dr/QfEqp1uRpt73qRjR4cZROaCvE7kEki6C9mzMTRDSXy5EZuynL6ouEBnoiiJnkKZtBOEweSez33CCk6r9v5eLQKLB/i5WorsMXWWSgsxAGeVhMrd0EFUcuxedQQJTWT89gA1TIIAdKFRaaYogpaF8i9UJyU6/U2SR1Yh3o0IcqJ8vRt1Ub++lOj5V7Jg4noP9oc07ypLbzcobIl8MMnHyyABMQbQ8XNB+BLxsJihCoRGN4TnqGZWWRbKs11vcifBDI3SWhEW7inzrYH/zLjT6iudKHlCJw5l/MLb55DMAA//iLyhOUVGBvIcRbFH5kmbvGHQiEY/LkAi53AAO1hTjO3ZmgoWnoGwglb6WdRkgDgPItyNKaclz2BONZhqwmCepnWSpvfXKZK5Lm1C3gv0/K+XbbwCRHjR/vYkkLTYTGUyW5b/66Z2tNjgEo7fiCYygjXzE0PzpH2xMG8prGtxmluvtT23DTiXcs9NEQ2L5zpwBvdRsV0hkhYf7aRgpuOidPSF0FAhMfhLbb9l+WhzI7xKx0o2wK+btJIjSZB89FtpZX+n703qmjYZthmunVmdeySX+FOBcsJBWuheNNK6GVq+vZ24AgcIRS32kBM9MqBKLBGUbvWT0gLL21QcvjAeD4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
