travis:
  secure:
    BINSTAR_TOKEN: VekYrsCZ3bycsADDwm31gke7+H0WClC5bDBFli/qP9glfT+/GJP5VaR/eSS3Tvrdh9Qydl5BX7/cS60o6fXGgCGAleoPViAqVhfcryBFJViyoqw2/P0Kr6YmnKp0CCwU0ZVFxFLb69UpCtvOQepCmjuCl5qNUz9bnp2MDBkeTnsOzfgA7rwGA6Gpl1vDmT0Z81qH+YqNgzZvVSVqhSe/GlymCLCjLFZy9Jf4N9KKwSjHch6ybe2jUW4OrUNBQbENTjTW13/eoLjKiqd/stMr3oEkg/sRPpr6PHaaTr0cMi6lyCxVhYk4f2eykA82jKMFCwZeM/0t6C1Jx9mmvi6PLYzHKZhVYqC10dZ7E9zkvOZeDyBAoac+N3nyWshMyrpFyRz7D25se3dbb1ifrSEhJmTyshWD4kAm8sLRZRZf3V8sEmlQduMKM8Yi0ufhDF0ALcSaQFs5GHVQjLcbSc/54MEAUW5LQ3SCFFEfGmPdwiOLrNTef1eRe4+0YAMFzX+GI5r8jmM7QYzKcW10mQjGaQTXUyvXBhHuzkXYj8d28mSpYWCnbPfN7jsSH5U/tFAl4CBJRFnsY6pMY1y61UXpHqKZZ8umynEb/okD5v0PT16Xedxw19oqlXZZMQYSgbMfb4k6uXwEtas+zBdHv+ewdABE3YScXTc2xO1MDoTXkzI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
